spring:
    # 数据库配置文件
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/classroombookingdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: 123456
    password: 123456
  mail:
    host: smtp.163.com  # 邮件服务器地址，比如smtp.qq.com
    port: 25  # 端口号
    username:   # 邮箱账号
    password:   # 密码或授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  servlet:
    multipart:
      #最大请求大小
      max-request-size: 100MB
      #单个文件大小
      max-file-size: 10MB
  application:
    name: classroom-booking-system
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #方式三开启驼峰命名
    map-underscore-to-camel-case: true

#配置事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

alioss:
  endpoint: 
  accessKeyId: 
  bucketName: 
  accessKeySecret: 
server:
  port: 8099